# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3abfeba91e5c551b546c8abedd6282bb123ce3429d1b65013b7363d589159e2e0f35c7867224d3d67a01785a874abf5eae290a1a2bef8c449be0a1139103a387

test:
  secret_key_base: ed2213628111145db61893befe94972ae01c7c478aa9900e34c4f86efc08703a252970db411bf06ae94c09d89c2a603f259343a22527c88c52727c15ff916702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
